# Generated by Django 5.0 on 2024-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
